### ISSUE TITLE
Plugins results are different depending on which link is used

### ISSUE THREAD

**Issue by longwa** [grails/grails3-plugins#13]
If you go to:

https://grails.org/plugins.html

It shows 184 plugins, all with out-dated versions.

If you visit:

https://plugins.grails.org/

It shows 228 plugins with correct versions.

Googling: "grails 3 plugins" returns the first result and even this GitHub repo description includes the bad link.

**Comment by sdelamo** [comment]
Please note that `https://grails.org/plugins.html` is embedding the `plugins.grails.org` portal. That it is to say the Grails 3 plugin information will be same.

https://grails.org/plugins/ is the old Grails 2 plugin portal.

**Comment by sheehan** [comment]
@sdelamo https://grails.org/plugins.html has an iframe pointing to https://sheehan.github.io/grails3-plugins/, which is the old location of the portal and has old data. I'll take down that page, but I also submitted a PR to redirect https://grails.org/plugins.html to http://plugins.grails.org/.

https://github.com/grails/grails-static-website/pull/71

**Comment by sheehan** [comment]
I took down the https://sheehan.github.io/grails3-plugins/ page, so https://grails.org/plugins.html now longer shows the outdated portal. It would be nice to have the redirect in place, but not required for this issue.
