### ISSUE TITLE
Owner links no longer work after redesign

### ISSUE THREAD

**Issue by erichelgeson** [grails/grails3-plugins#15]
eg: http://plugins.grails.org/plugin/9ci/q/owner:9ci

**Comment by sheehan** [comment]
Looks like an issue with relative urls. If you go to 

http://plugins.grails.org/q/label:TaskExecutor

and click on `vahid` it goes to

http://plugins.grails.org/q/q/owner:vahid

**Comment by sheehan** [comment]
It still happens if you go to

http://plugins.grails.org/plugin/vahid/ajaxdependancyselection

and click on `vahid`
